# Generated by Django 4.1.7 on 2023-04-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_thumbnail_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
    ]
